spring:
  profiles:
      include: aws

  redis:
    host: localhost
    port: 6379

  jpa:
#    database: mysql   # 추가 해준 부분
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
          show_sql: true
          format_sql: true
          hbm2ddl:
            auto: update
    open-in-view: false
  thymeleaf:
      cache: 'false'
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  # 원하는 파일 크기로 설정
      max-request-size: 10MB  # 원하는 요청 크기로 설정

server:
  port: 5501
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html
    min-response-size: 2048
#
#management:
#  endpoints:
#     health:
#       show-details: always

logging:
  level:
    org.hibernate.type.descriptor.sql: DEBUG