version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

  spring-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5501:5501
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/mydatabase

volumes:
  mongodata: